name: Build docs on release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'leanprover-community'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lean
        uses: leanprover/lean-action@v1
        with:
          test: false
          lint: false
          use-github-cache: true

      - name: Build Docs
        working-directory: docs
        run: lake build -q

      - name: Compress Docs
        working-directory: docs
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          tar -czf docs-${TAG_NAME}.tar.gz doc doc-data
          zip -rq docs-${TAG_NAME}.zip doc doc-data

      - name: Release Docs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            docs/docs-${{ github.ref_name }}.tar.gz
            docs/docs-${{ github.ref_name }}.zip
          fail_on_unmatched_files: true

      - name: Deploy Docs
        run: |
          git config user.name "leanprover-community-batteries-bot"
          git config user.email "leanprover-community-batteries-bot@users.noreply.github.com"
          git checkout -b docs
          git add docs/doc docs/doc-data
          git commit -m "chore: generate docs"
          git push origin docs
