name: Merge conflicts

on:
  schedule:
    - cron: '*/60 * * * *' # run every 60 minutes

jobs:
  main:
    if: github.repository_owner == 'leanprover-community'
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.MATHLIB_MERGE_CONFLICTS_APP_ID }}
          private-key: ${{ secrets.MATHLIB_MERGE_CONFLICTS_PRIVATE_KEY }}
      # The create-github-app-token README states that this token is masked and will not be logged accidentally.
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # v3.0.3
        with:
          dirtyLabel: "merge-conflict"
          repoToken: ${{ steps.app-token.outputs.token }}
